routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('app.logout');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::middleware(['auth'])->group(function (){
    Route::get('products',[App\Http\Controllers\Cms\ProductController::class,'index']);
    Route::resource('products',App\Http\Controllers\Cms\ProductController::class);
    Route::post('updateProducts',[App\Http\Controllers\Cms\ProductController::class,'update']);

    Route::resource('sales_orders',\App\Http\Controllers\Cms\SaleOrderController::class);
    Route::get('/findVehicle',[\App\Http\Controllers\Cms\SaleOrderController::class,'findVehicle']);
    Route::get('/showProduct',[\App\Http\Controllers\Cms\SaleOrderController::class,'showProduct']);
    Route::get('/addProduct',[\App\Http\Controllers\Cms\SaleOrderController::class,'addProduct']);


    Route::resource('vehicles',App\Http\Controllers\Cms\VehicleController::class);
    Route::post('updateVehicles',[App\Http\Controllers\Cms\VehicleController::class,'update']);

    /*
     *  Datatable Controller
     */
    Route::get('list_products',[\App\Http\Controllers\Datatable\ProductController::class,'getAll']);
    Route::get('list_vehicles',[\App\Http\Controllers\Datatable\VehicleController::class,'getAll']);

    Route::get('list_sale_orders',[\App\Http\Controllers\Datatable\SaleOrderController::class,'getAll']);

});

app/Models/Entity/SaleOrder.php
<?php

namespace App\Models\Entity;

use App\Models\AppModel;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SaleOrder extends AppModel
{
    protected $table    =   'sale_orders';


    protected $fillable =   [
        'number',
        'vehicle_id',
        'date',
        'user_id'
    ];
}

app/Models/Table/SaleOrderTable.php
<?php

namespace App\Models\Table;

use App\Models\Entity\SaleOrder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SaleOrderTable extends SaleOrder
{
    public function order_items()
    {
        return $this->hasMany(SaleOrderDetailTable::class, 'sale_order_id');
    }

    public function vehicles()
    {
        return $this->belongsTo(VehicleTable::class,'vehicle_id');
    }

}

app/Http/Controllers/Cms/SaleOrderController.php
<?php

namespace App\Http\Controllers\Cms;

use App\Http\Controllers\ApiController;
use App\Http\Controllers\Controller;
use App\Http\Requests\Transaction\CreateSaleOrderRequest;
use App\Services\Product\ProductService;
use App\Services\SaleOrder\SaleOrderService;
use App\Services\Vehicle\VehicleService;
use Illuminate\Http\Request;

class SaleOrderController extends ApiController
{
    protected $saleOrderService;
    protected $vehicleService;
    protected $productService;

    public function __construct(
        ProductService $productService,
        VehicleService $vehicleService,
        SaleOrderService $saleOrderService,
        Request $request)
    {
        parent::__construct($request);
        $this->saleOrderService  =   $saleOrderService;
        $this->vehicleService   =   $vehicleService;
        $this->productService   =   $productService;
    }

    public function index()
    {
        return view("sale_order.index");
    }

    public function create()
    {
        return view("sale_order.create");
    }

    public function findVehicle(Request $request): \Illuminate\Http\JsonResponse
    {
        $input  =   $request->all();
        $result =   $this->vehicleService->getByCode($input);

        try {
            if ($result->success) {
                $response = $result->data;
                return $this->sendSuccess($response, $result->message, $result->code);
            }

            return $this->sendError($result->data, $result->message, $result->code);
        } catch (\Exception $exception) {
            return $this->sendError($exception->getMessage(),"",500);
        }
    }

    public function showProduct(Request $request): \Illuminate\Http\JsonResponse
    {
        $input  =   $request->all();
        return $this->productService->loadProduct($input);
    }

    public function addProduct(Request $request): \Illuminate\Http\JsonResponse
    {
        $input  =   $request->all();
        return $this->productService->addProduct($input);
    }

    public function store(CreateSaleOrderRequest $request)
    {
        $input  =   $request->all();
        $result =   $this->saleOrderService->create($input);

        try {
            if ($result->success) {
                $response = $result->data;
                return $this->sendSuccess($response, $result->message, $result->code);
            }

            return $this->sendError($result->data, $result->message, $result->code);
        } catch (\Exception $exception) {
            return $this->sendError($exception->getMessage(),"",500);
        }
    }
}

app/Http/Controllers/Datatable/SaleOrderController.php
<?php

namespace App\Http\Controllers\Datatable;

use App\Http\Controllers\Controller;
use App\Services\SaleOrder\SaleOrderService;
use Illuminate\Http\Request;

class SaleOrderController extends Controller
{
    protected $saleOrderService;

    /**
     * @param SaleOrderService $saleOrderService
     */
    public function __construct(SaleOrderService $saleOrderService)
    {
        $this->saleOrderService = $saleOrderService;
    }

    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function getAll()
    {
        return $this->saleOrderService->getAll();
    }
}

resources/views/sale_order/create.blade.php
@component('layouts.app')
    @section('title','Transaction Sale Order')
@section('heading')
    <div class="d-flex align-items-baseline flex-wrap mr-5">
        <!--begin::Page Title-->
        <h2 class="d-flex align-items-center text-dark font-weight-bold my-1 mr-3">Transaction</h2>
        <!--end::Page Title-->
        <!--begin::Breadcrumb-->
        <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold my-2 p-0">
            <li class="breadcrumb-item text-muted">
                <a href="#" class="text-muted">Transaction</a>
            </li>
            <li class="breadcrumb-item text-muted">
                <a href="{{route('sales_orders.index')}}" class="text-muted">Transaction Sale Order</a>
            </li>
            <li class="breadcrumb-item text-muted">
                <a href="#" class="text-muted">Create Order</a>
            </li>
        </ul>
        <!--end::Breadcrumb-->
    </div>
@endsection
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <!--begin::Card-->
            <div class="card card-custom gutter-b example example-compact">
                <div class="card-header">
                    <h3 class="card-title">Create Order</h3>
                </div>
                <!--begin::Form-->
                <form class="form" autocomplete="off" onsubmit="createSellout(this,event)" method="POST">
                    <div class="card-body">
                        <div class="mb-15">
                            <div class="form-group row">
                                <label class="col-form-label col-lg-3 col-sm-12">Find Vehicle</label>
                                <div class="col-lg-4 col-md-12 col-sm-12 input-group">
                                    <input type="text"
                                           class="form-control" id="vehicle" name="vehicle">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" id="BtnSave" onclick="findVehicle(event)"
                                                type="button">Find!
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-3 col-form-label">Vehicle</label>
                                <div class="col-lg-4">
                                    <input type="text" disabled class="form-control" id="name" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="kt-portlet__body col-md-12">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th colspan="3" style="text-align: center;">TABLE PRODUCT</th>
                                </tr>
                                <tr>
                                    <th>Name Product</th>
                                    <th style="width: 100px">Qty</th>
                                    <th style="width: 10px">Action</th>
                                </tr>
                                </thead>
                                <tbody id="productItems"></tbody>
                                <tr>
                                    <td colspan="3">
                                        <a href="#" id="btnProduct" onclick="showAddProduct(this, event)"
                                           class="btn btn-success mr-2">
                                            <i class="la la-plus"></i>
                                            Add Product
                                        </a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-lg-12 text-lg-right">
                                <button type="submit" id="saveBtn" class="btn btn-success mr-2">Save</button>
                                <a href="{{route('sales_orders.index')}}" class="btn btn-secondary">Cancel</a>
                            </div>
                        </div>
                    </div>
                </form>
                <!--end::Form-->
            </div>
            <!--end::Card-->
        </div>
    </div>

<div class="modal fade bs-modal-lg" id="large" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title float-left">Product</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body data-detail">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="getCheckedBoxesSellout('checkboxName')">Add</button>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
    <script src="{{asset('app/dist/sale_order.js')}}" type="text/javascript"></script>
@endsection
@endcomponent

resources/views/sale_order/index.blade.php
@component('layouts.app')
    @section('title','Transaction Sale Order')
@section('heading')
    <div class="d-flex align-items-baseline flex-wrap mr-5">
        <!--begin::Page Title-->
        <h2 class="d-flex align-items-center text-dark font-weight-bold my-1 mr-3">Setting</h2>
        <!--end::Page Title-->
        <!--begin::Breadcrumb-->
        <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold my-2 p-0">
            <li class="breadcrumb-item text-muted">
                <a href="#" class="text-muted">Transaction</a>
            </li>
            <li class="breadcrumb-item text-muted">
                <a href="{{route('sales_orders.index')}}" class="text-muted">Transaction Sale Order </a>
            </li>
        </ul>
        <!--end::Breadcrumb-->
    </div>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card card-custom">
                <div class="card-header">
                    <div class="card-title">
    			<span class="card-icon">
    				<i class="flaticon2-user-1 text-primary"></i>
    			</span>
                        <h3 class="card-label">Transaction Sale Order</h3>
                    </div>
                    <div class="card-toolbar">
                        <!--begin::Button-->
                        <a href="{{route('sales_orders.create')}}" class="btn btn-primary font-weight-bolder">
    				<span class="svg-icon svg-icon-md">
    					<!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
    					<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
    						<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
    							<rect x="0" y="0" width="24" height="24" />
    							<circle fill="#000000" cx="9" cy="15" r="6" />
    							<path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
    						</g>
    					</svg>
                        <!--end::Svg Icon-->
    				</span>New Record</a>
                        <!--end::Button-->
                    </div>
                </div>
                <div class="card-body">
                    <!--begin: Datatable-->
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover" id="kt_datatable_sale_orders" style="margin-top: 13px !important">
                            <thead>
                            <tr>
                                <th>Number</th>
                                <th>Date</th>
                                <th>Vehicle</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                    <!--end: Datatable-->
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="{{asset('app/dist/sale_order.js')}}" type="text/javascript"></script>
@endsection
@endcomponent

resources/views/sale_order/show.blade.php
<?php